In [1]:
import pandas as pd

In [10]:
df=pd.read_csv(r'C:\Users\samir saiyed\Desktop\project\House_price_prediction\housing\artifact\data_ingestion\2023-07-15-15-43-57\ingested_data\train\housing.csv')

In [5]:
os.getcwd()

'c:\\Users\\samir saiyed\\Desktop\\project\\House_price_prediction\\notebook'

In [6]:
os.chdir('c:\\Users\\samir saiyed\\Desktop\\project\\House_price_prediction')

In [11]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   
3    -117.13     32.75                24.0       1877.0           519.0   
4    -118.70     34.28                27.0       3536.0           646.0   

   population  households  median_income  median_house_value ocean_proximity  
0      2237.0       706.0         2.1736             72100.0          INLAND  
1      2015.0       768.0         6.3373            279600.0      NEAR OCEAN  
2       667.0       300.0         2.8750             82700.0          INLAND  
3       898.0       483.0         2.2264            112500.0      NEAR OCEAN  
4      1837.0       580.0         4.4964            238300.0       <1H OCEAN

In [12]:
df.shape

(16512, 10)

In [24]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [25]:
x,y = df.drop(columns='median_house_value'),df[['median_house_value']]

In [26]:
x.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   
3    -117.13     32.75                24.0       1877.0           519.0   
4    -118.70     34.28                27.0       3536.0           646.0   

   population  households  median_income ocean_proximity  
0      2237.0       706.0         2.1736          INLAND  
1      2015.0       768.0         6.3373      NEAR OCEAN  
2       667.0       300.0         2.8750          INLAND  
3       898.0       483.0         2.2264      NEAR OCEAN  
4      1837.0       580.0         4.4964       <1H OCEAN

In [27]:
y.head()

median_house_value
0             72100.0
1            279600.0
2             82700.0
3            112500.0
4            238300.0

In [28]:
x.shape

(16512, 9)

In [29]:
y.shape

(16512, 1)

In [30]:
x.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [31]:
from sklearn.impute import SimpleImputer

In [32]:
simpleimputer = SimpleImputer(strategy='median')

In [34]:
numerical_columns = x.drop(['ocean_proximity'],axis=1)

In [35]:
simpleimputer.fit_transform(numerical_columns)

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [37]:
df = simpleimputer.transform(numerical_columns)

In [40]:
simpleimputer.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [41]:
simpleimputer.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [43]:
x.ocean_proximity.value_counts()

<1H OCEAN     7277
INLAND        5262
NEAR OCEAN    2124
NEAR BAY      1847
ISLAND           2
Name: ocean_proximity, dtype: int64

In [44]:
SimpleImputer(strategy="most_frequent")

SimpleImputer(strategy='most_frequent')

In [47]:
from sklearn.base import BaseEstimator, TransformerMixin
# Own custom transformer 
class FeatureGenerator(BaseEstimator, TransformerMixin):
    def __init__(self,strategy = "median"):
        self.strategy = strategy

    def fit(self,X):
        self.features_ = X.columns
        self.statistic_=[]
        for column in X.columns:
            self.statistic_.append(X[column].median())


    def transform(self,X:pd.DataFrame):
        for idx,column in enumerate(x.columns):
            X[column].fillna(self.statistic_[idx])
        return X

    def fit_transfom(self,X):
        self.fit(X)
        return self.transform(X)


In [45]:
for idx,column in enumerate(x.columns):
    print(idx, column)

0 longitude
1 latitude
2 housing_median_age
3 total_rooms
4 total_bedrooms
5 population
6 households
7 median_income
8 ocean_proximity


# Use this pipeline for any project

In [53]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

In [73]:
num_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy="median")),
    
    ('scaling',StandardScaler())
])

In [74]:
cat_pipeline = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy="most_frequent")),
    ('onehoencoder',OneHotEncoder()),
    ('scaling',StandardScaler(with_mean=False))
])

In [75]:
df=pd.read_csv(r'C:\Users\samir saiyed\Desktop\project\House_price_prediction\housing\artifact\data_ingestion\2023-07-15-15-43-57\ingested_data\train\housing.csv')

In [76]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [77]:
num_column_name = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income']

In [78]:
cat_column_name = ['ocean_proximity']

In [79]:
preprocessing = ColumnTransformer([
    ('num_pipeline',num_pipeline,num_column_name),
    ('cat_pipeline',cat_pipeline,cat_column_name)
])

In [80]:
preprocessing

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['longitude', 'latitude', 'housing_median_age',
                                  'total_rooms', 'total_bedrooms', 'population',
                                  'households', 'median_income']),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehoencoder',
                                                  OneHotEncoder()),
                                                 ('scaling',
                                                  StandardScaler(with_mean=False))]),
                                 ['ocean_proximity'])])

In [81]:
preprocessing.fit_transform(df)

array([[-0.94135046,  1.34743822,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.17178212, -1.19243966, -1.72201763, ...,  0.        ,
         0.        ,  2.9869105 ],
       [ 0.26758118, -0.1259716 ,  1.22045984, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ...,  0.        ,
         0.        ,  0.        ],
       [-1.56080303,  1.2492109 , -1.1653327 , ...,  0.        ,
         0.        ,  0.        ],
       [-1.28105026,  2.02567448, -0.13148926, ...,  0.        ,
         0.        ,  0.        ]])

In [82]:
!pip install dill

  Using cached dill-0.3.6-py3-none-any.whl (110 kB)


In [83]:
import dill

In [91]:
with open('preprocessing.pkl',"wb") as prep_file:
    dill.dump(preprocessing,prep_file)

In [90]:
with open('preprocessing.pkl',"rb") as file_obj:
    preprocessing_loaded_obj = dill.load(file_obj)

FileNotFoundError: [Errno 2] No such file or directory: 'preprocessing1.pkl'

In [ ]:
preprocessing.transform(new_df)

In [93]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [96]:
x

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -121.46     38.52                29.0       3873.0           797.0   
1        -117.23     33.09                 7.0       5320.0           855.0   
2        -119.04     35.37                44.0       1618.0           310.0   
3        -117.13     32.75                24.0       1877.0           519.0   
4        -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
16507    -117.07     33.03                14.0       6665.0          1231.0   
16508    -121.42     38.51                15.0       7901.0          1422.0   
16509    -122.72     38.44                48.0        707.0           166.0   
16510    -122.70     38.31                14.0       3155.0           580.0   
16511    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income ocean_proximity  
0          2237.0       706.0         2.1736          INLAND  
1          2015.0       768.0         6.3373      NEAR OCEAN  
2           667.0       300.0         2.8750          INLAND  
3           898.0       483.0         2.2264      NEAR OCEAN  
4          1837.0       580.0         4.4964       <1H OCEAN  
...           ...         ...            ...             ...  
16507      2026.0      1001.0         5.0900       <1H OCEAN  
16508      4769.0      1418.0         2.8139          INLAND  
16509       458.0       172.0         3.1797       <1H OCEAN  
16510      1208.0       501.0         4.1964       <1H OCEAN  
16511       625.0       197.0         3.1319          INLAND  

[16512 rows x 9 columns]

In [100]:
import numpy as np
y=np.array(y)